### ISSUE TITLE
Wrong theme url

### ISSUE THREAD

**Issue by eonlab** [Shipu/themevel#11]
Hi,
Using: 
`<link rel="stylesheet" href="{{ themes('css/app.css') }}">`

in a view it creates this url: http://www.somedomain.com/<theme_name>/assets/css/app.css
but it should be http://www.somedomain.com/themes/<theme_name>/assets/css/app.css that corresponds to the symlink created in the public folder. Is this a bug or am I doing something wrong?

Thanks

**Comment by Shipu** [comment]
Can you please provide you `app/config/theme.php` .

**Comment by Shipu** [comment]
Fixed in `v1.6`
