### ISSUE TITLE
How to change default directory?

### ISSUE THREAD

**Issue by assoft** [Shipu/themevel#12]
I want to change the default directory

My Theme Config "theme.php":
`'theme_path' => base_path('resources/themes'),`

resources/themes/default/views/welcome.blade.php:
`<link rel="stylesheet" href="{{ themes('css/app.css') }}">`

browser response: 
`http://theme.dev/urces/themes/default/assets/css/app.css`

Where does **"urces"** come from?

Would you test the folder change?

There is a problem here.

Thank you

**Comment by Shipu** [comment]
what's you env app url ?

**Comment by Shipu** [comment]
please update package. Bug Fixed. use `v1.6`
