### ISSUE TITLE
Theme trying to load when null or blanks

### ISSUE THREAD

**Issue by dariusj18** [Shipu/themevel#19]
If the active theme is configured as null or blank there doesn't seem to be any reason a theme should attempt to be loaded.

`Theme [  ] not found! Maybe you're missing a theme.json file.`

**Comment by Shipu** [comment]
every theme must be have theme.json file.

**Comment by dariusj18** [comment]
That is not what I was getting at.

Currently the service throws an error if the theme does not exists, however it also considers null and blank theme names as viable theme.  Ideally if the theme name is null or blank it should just not try and load a theme automatically.
