### ISSUE TITLE
support for laravel 5.6 and 5.7 needed.

### ISSUE THREAD

**Issue by ghost** [Shipu/themevel#21]

**Comment by HDVinnie** [comment]
second this

**Comment by 8082** [comment]
+1

**Comment by raminr63** [comment]
is it possible?

**Comment by majost-colombia** [comment]
The package does not support laravel 5.7?

**Comment by AhmedMFathy** [comment]
+1

**Comment by K4q4m3** [comment]
What is the problem with Laravel 5.7? 
I'm using this package with Laravel 5.8

**Comment by AhmedMFathy** [comment]
Theme set is not working

**Comment by adrielgro** [comment]
+1

**Comment by Shipu** [comment]
themevel already support laravel 5.8.
use facades for set theme like `Shipu\Themevel\Facades\Theme::set('themeone');` Thank you.
