### ISSUE TITLE
Problem when trying to create a new Theme

### ISSUE THREAD

**Issue by lucacv** [Shipu/themevel#23]
I'm trying to execute the command `php artisan theme:create your_theme_name` but I received an error `mkdir() permission denied` so I have tried to run the command with `sudo` and this happens:

![image](https://user-images.githubusercontent.com/36013049/61389889-fe471c00-a8b9-11e9-845e-21d160ce10cd.png)

**Comment by lucacv** [comment]
This is the full error:

>    ErrorException  : mkdir(): Permission denied
> 
>   at /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:466
>     462|         if ($force) {
>     463|             return @mkdir($path, $mode, $recursive);
>     464|         }
>     465| 
>   > 466|         return mkdir($path, $mode, $recursive);
>     467|     }
>     468| 
>     469|     /**
>     470|      * Move a directory.
> 
>   Exception trace:
> 
>   1   mkdir("/theme_2")
>       /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:466
> 
>   2   Illuminate\Filesystem\Filesystem::makeDirectory("/theme_2")
>       /home/vagrant/*****/vendor/shipu/themevel/src/Console/ThemeGeneratorCommand.php:177
> 
>   3   Shipu\Themevel\Console\ThemeGeneratorCommand::makeDir("/theme_2")
>       /home/vagrant/*****/vendor/shipu/themevel/src/Console/ThemeGeneratorCommand.php:107
> 
>   4   Shipu\Themevel\Console\ThemeGeneratorCommand::handle()
>       /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
> 
>   5   call_user_func_array([])
>       /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
> 
>   6   Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
>       /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:90
> 
>   7   Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
>       /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:34
> 
>   8   Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
>       /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Container/Container.php:576
> 
>   9   Illuminate\Container\Container::call()
>       /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Console/Command.php:183
> 
>   10  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
>       /home/vagrant/*****/vendor/symfony/console/Command/Command.php:255
> 
>   11  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
>       /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Console/Command.php:170
> 
>   12  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>       /home/vagrant/*****/vendor/symfony/console/Application.php:921
> 
>   13  Symfony\Component\Console\Application::doRunCommand(Object(Shipu\Themevel\Console\ThemeGeneratorCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>       /home/vagrant/*****/vendor/symfony/console/Application.php:273
> 
>   14  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>       /home/vagrant/*****/vendor/symfony/console/Application.php:149
> 
>   15  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>       /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Console/Application.php:90
> 
>   16  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>       /home/vagrant/*****/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php:133
> 
>   17  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
>       /home/vagrant/*****/artisan:37

**Comment by MitchellWeg** [comment]
Run this command:
`php artisan vendor:publish --provider="Shipu\Themevel\Providers\ThemevelServiceProvider"`

**Comment by Shipu** [comment]
please update `v2.1` or higher.
