### ISSUE TITLE
Make this less opinionated

### ISSUE THREAD

**Issue by ju5t** [Shipu/themevel#27]
Although I really like what you have done here I think it could be a little less opinionated. 

For example it's extensive use of `ucfirst()` could be better. It shouldn't decide for us how to case our description or author. Defaulting the author to your own name isn't something I would personally do either.

The same can be said about the symlink. This defaults to 'Themes'. This is personal preference but I would probably use a different name for this. It would be great if we could configure the name of the symlink instead.

Happy to help with PR's of course.

**Comment by Shipu** [comment]
everything is configurable and changeable. please read the documentation.

**Comment by ju5t** [comment]
I'm only trying to help, I'm happy to help with PR's too, but if you're not open to improvements I won't bother.

`ucfirst()` capitalises strings. Sure, you can change it afterwards, but if I tell it capitalise my name in a certain manner, I don't expect this package to change things. 

A lot of phrases in this package feel unprofessional. The code itself might be awesome, but people do judge a book by its cover, and I'm sure it makes people a little reluctant to use this package.

Could you point me to the documentation where it explains how to change the symlink? Because as far as I can see it's hardcoded. You HAVE to use 'Themes' and I don't want to.

https://github.com/Shipu/themevel/blob/402250689a5e588298a7a89900e0f3d528234891/src/Providers/ThemevelServiceProvider.php#L22

**Comment by Shipu** [comment]
In `v2.2.1` version you can change symlink_path by your `themevel` config and remove default author name. Thanks for your support and you can help me with PR.

https://github.com/Shipu/themevel/blob/96fea6a5b0edea243fe9e259acaa14b6717b4372/config/theme.php#L47

https://github.com/Shipu/themevel/blob/96fea6a5b0edea243fe9e259acaa14b6717b4372/src/Providers/ThemevelServiceProvider.php#L22
