### ISSUE TITLE
Issue in asset path from parent theme

### ISSUE THREAD

**Issue by patilvishalvs** [Shipu/themevel#28]
There is an issue when getting assets path from parent theme on windows machine. Given below patch may help resolve the issue.

`$themePath = str_replace(base_path().DIRECTORY_SEPARATOR, '', $this->getThemeInfo($themeInfo->get('parent'))->get('path') ).'/';
`
[parent-them-assets-path.txt](https://github.com/Shipu/themevel/files/3464364/parent-them-assets-path.txt)

**Comment by Shipu** [comment]
added thanks dear.
