### ISSUE TITLE
Problem when trying to create a new Theme in Laravel 6.0

### ISSUE THREAD

**Issue by FlavioCostaeSilva** [Shipu/themevel#29]
Hi,

An exception occurs after "What is theme description? " response.

/![Captura de tela de 2019-10-08 14-08-07](https://user-images.githubusercontent.com/17554616/66416996-73b41b80-e9d5-11e9-962d-10a6211a49ed.png)

**Comment by Shipu** [comment]
Which laravel version you use.

**Comment by rifalpg** [comment]
We still waiting update for Laravel 6, but you can try to change manualy.

On `ThemeGeneratorCommand.php`, try to change `title_case `with `Str::title`
add `use Illuminate\Support\Str;`

And if you get error `Invalid argument supplied for foreach()`, open `ThemevelServiceProvider.php` and change:
`$this->mergeConfigFrom($configPath, 'themevel')`; to 
`$this->mergeConfigFrom($configPath, 'theme');`

Don't forget to `php artisan config:clear`

**Comment by Shipu** [comment]
please update `v2.2.1` or higher.
