### ISSUE TITLE
Cannot change "Themes" folder

### ISSUE THREAD

**Issue by oasin** [Shipu/themevel#37]
I installed V2.1 but whenever i change "Themes" folder to either "themes" or "files" or anything else i get error 404

**Comment by Shipu** [comment]
you need composer update

**Comment by oasin** [comment]
I already updated composer but still gets error

**Comment by Shipu** [comment]
it fixed at `v2.2.2` version. can you please share your installed version?

**Comment by oasin** [comment]
My current installation is         "shipu/themevel": "^2.2"
on Laravel 7

**Comment by Shipu** [comment]
hope it will solve `v2.2.2`
