### ISSUE TITLE
Bug in ThemeGeneratorCommand : title_case

### ISSUE THREAD

**Issue by ghost** [Shipu/themevel#40]
Hi.

There is a little bug, when i launched this command (at description) : 

```
  Call to undefined function Shipu\Themevel\Console\title_case()
  at vendor/shipu/themevel/src/Console/ThemeGeneratorCommand.php:146
```

I have checked the code source, indeed, since laravel 5.7, the method title_case is remplaced by **Str::title**
See manual : https://laravel.com/docs/7.x/helpers#method-title-case

I will try to do a pull request to fix it. ( It is my first time). Maybe it is better to create another branches : 1 for < 5.7 and 1 another for >= 5.7.

( I love your package :-) )

Best regards.

**Comment by Shipu** [comment]
Merged
