### ISSUE TITLE
Laravel Mix() helper doesn't work

### ISSUE THREAD

**Issue by elfeffe** [Shipu/themevel#44]
It tries to reference always to public path

**Comment by elfeffe** [comment]
How to use theme_mix?

**Comment by elfeffe** [comment]
I have it working, but I had to pass my theme's folder as $manifest path. theme_mix should handle it, no?
Am I using it wrong?

**Comment by supryantowp** [comment]
me too same error

**Comment by Shipu** [comment]
```
theme_mix('your_asset_path')
```
or 
```
theme_mix('theme_namespace:your_asset_path')
```
or 
```
theme_mix('theme_namespace:your_asset_path', 'your manifest directory')
```
as like as laravel mix helper.

**Comment by elfeffe** [comment]
@Shipu can you supply a demo theme? I think the mix-manifest.json also needs some changes

**Comment by elfeffe** [comment]
I mean webpack.mix.js
We have to make some changes there too, right?

**Comment by Shipu** [comment]
@elfeffe i have plan to share demo app. in your mix add full path of theme asset.
