### ISSUE TITLE
I am interested in using the themevel... 

### ISSUE THREAD

**Issue by raghavan2004** [Shipu/themevel#58]
I am interested in creating a interface like wordpress for choosing the theme can i use this package ... I am little confused so writing this message..

please guide me

**Comment by Shipu** [comment]
i am on it but if you want then you can. i have no issues or you can contribute.

**Comment by raghavan2004** [comment]
Hi Shipu/themevel,

Thanks for your reply.

I will try using the package and will also contribute

Regards,
Vijey

**Comment by Shipu** [comment]
Great.
