### ISSUE TITLE
symlink(): No such file or directory 

### ISSUE THREAD

**Issue by victorybiz** [Shipu/themevel#61]
ErrorException
symlink(): No such file or directory 

after installation on Laravel v8.78.1 (PHP v8.1.1)

**Comment by victorybiz** [comment]
@Shipu I think this issue with symlink creation condition checking was fixed in PR #59 but no release yet... Please review this.

**Comment by chienle** [comment]
@victorybiz don't worry, 
I have same your issue, I fixed it with action delete symlink `theme` at folder `public/themes`

**Comment by Shipu** [comment]
Done [v3.0.3](https://github.com/Shipu/themevel/releases/tag/v3.0.3). @victorybiz
